# This is a basic workflow to help you get started with Actions

name: Update data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  thistime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: pip3 install -r requirements.txt
      - name: Update data
        run: python3 src/update_data.py
      - name: Commit changes
        run: |
          git config --global user.name 'Automated workflow - Update data'
          git config --global user.email 'kiss-oliver@users.noreply.github.com'
          git add -A
          git commit -m "Committed by Update data workflow."
          git push
