# This is a basic workflow to help you get started with Actions

name: Update data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  thistime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Echo time
        run: |
          echo Hello
          date +"%T" >> time.txt
      - name: Commit report
        run: |
          git config --global user.name 'Automated workflow'
          git config --global user.email 'kiss-oliver@users.noreply.github.com'
          git add -A
          git commit -m "Update made by Action"
          git push
