# This is a basic workflow to help you get started with Actions

name: Update data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  thistime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Echo time
        run: |
          echo Hello
          date +"%T" >> time.txt
          git add time.txt
          git commit -m 'Commit by update data workflow'
